version: "3"
services:
  install:
      platform: linux/amd64
      build:
        context: .
        dockerfile: Dockerfile
      image: ghcr.io/raygamedev/ansible:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
